name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '0,15 * * * *'

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v0.4
        with:
          upstream: 0xGG/crossnote    # set the upstream repo
          branch: /feat/caret-color   # set the branch to merge
